### PR TITLE
Add BQN language

### PR DESCRIPTION
**Pull request by skykanin**
Add support for the BQN language as it's now [passed](https://github.com/search?q=NOT+is%3Afork+path%3A*.bqn&type=code) the 2k unique file threshold.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.bqn
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/Brian-ED/rayed-bqn
    - Sample license(s):
  - [x] I have included a syntax highlighting grammar: [[URL to grammar repo]](https://github.com/razetime/bqn-vscode)
      
  - [x] I have added a color
    - Hex value: `#21584F`
    - Rationale:  This is the main colour associated with BQN
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by skykanin** [comment]
> > Add support for the BQN language as it's now [passed](https://github.com/search?q=NOT+is%3Afork+path%3A*.bqn&type=code) the 2k unique file threshhold.
> 
> Not quite. [1 repo alone](https://github.com/acmeism/RosettaCodeData) accounts for 380 of those files.

So how many files can a single repository account for as a percentage of the threshold?

**Comment by lildude** [comment]
> So how many files can a single repository maximally account for as a percentage of the threshold?

It's not about how many files a repo has but rather how widely used the extension is. If there is an indication of a single user or repo having a disproportionate impact on the usage, I'll exclude it... 2000 files spread across 200 repos is a lot more indicative of widespread usage than 2000 files in a single repo.

**Comment by skykanin** [comment]
> You'll also need to run script/list-grammars also run at the bottom of that script.

When I try to run `script/list-grammars` I get the following error:
```
./script/list-grammars
Traceback (most recent call last):
        9: from ./script/list-grammars:4:in `<main>'
        8: from ./script/list-grammars:4:in `require'
        7: from /home/skykanin/Projects/linguist/lib/linguist.rb:5:in `<top (required)>'
        6: from /home/skykanin/Projects/linguist/lib/linguist.rb:5:in `require'
        5: from /home/skykanin/Projects/linguist/lib/linguist/language.rb:9:in `<top (required)>'
        4: from /home/skykanin/Projects/linguist/lib/linguist/language.rb:9:in `require'
        3: from /home/skykanin/Projects/linguist/lib/linguist/classifier.rb:1:in `<top (required)>'
        2: from /home/skykanin/Projects/linguist/lib/linguist/classifier.rb:1:in `require'
        1: from /home/skykanin/Projects/linguist/lib/linguist/tokenizer.rb:2:in `<top (required)>'
/home/skykanin/Projects/linguist/lib/linguist/tokenizer.rb:2:in `require': cannot load such file -- linguist/linguist (LoadError)
```
Seems that it's unable to load `linguist/linguist` from `lib/linguist/tokenizer.rb` for some reason.

**Comment by lildude** [comment]
You need to install the linguist gem... or use the Codespace we recommend.

**Comment by lildude** [comment]
Yes, it's the `github-linguist` gem. If you've got it installed, try running `bundle exec ./script/list-grammars` else try the Codespace.

**Comment by mlochbaum** [comment]
I've indexed the following 27 Advent of Code repositories, which brings [this search](https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.bqn+NOT+repo%3Aacmeism%2FRosettaCodeData) up to 2k.

```
repo:AlexDikelsky/puzzles OR repo:alephno/aoc2021 OR repo:alvinvoo/aoc2021 OR repo:arwn/aoc2021 OR repo:dancek/bqn-advent2021 OR repo:frasiyav/AoC2021 OR repo:m-lima/advent-of-code-2021 OR repo:AugustUnderground/AoC2022 OR repo:Choram/AoC2022BQN OR repo:Nhlest/AoC2022 OR repo:SamuelSarle/advent OR repo:akamayu-ouo/AoC OR repo:bddean/aoc OR repo:dancek/bqn-advent2022 OR repo:dankeyy/aoc22 OR repo:dgkf/advent-of-code OR repo:eissplitter/aoc-2022 OR repo:extorious/aoc2022 OR repo:felixr/advent-of-code OR repo:juriad/advent2022 OR repo:mpizzzle/AdventOfCode OR repo:saltysylvi/bqn-aoc2022 OR repo:RKBethke/aoc23-bqn OR repo:azenna/advent-of-code-2023 OR repo:icendoan/aoc OR repo:qqii/advent-of-code-2023 OR repo:timmarinin/aoc2023 OR repo:dlozeve/aoc2023
```

I note that file totals frequently don't add up right: the [full search](https://github.com/search?type=code&q=path%3A*.bqn+%28repo%3AAlexDikelsky%2Fpuzzles+OR+repo%3Aalephno%2Faoc2021+OR+repo%3Aalvinvoo%2Faoc2021+OR+repo%3Aarwn%2Faoc2021+OR+repo%3Adancek%2Fbqn-advent2021+OR+repo%3Afrasiyav%2FAoC2021+OR+repo%3Am-lima%2Fadvent-of-code-2021+OR+repo%3AAugustUnderground%2FAoC2022+OR+repo%3AChoram%2FAoC2022BQN+OR+repo%3ANhlest%2FAoC2022+OR+repo%3ASamuelSarle%2Fadvent+OR+repo%3Aakamayu-ouo%2FAoC+OR+repo%3Abddean%2Faoc+OR+repo%3Adancek%2Fbqn-advent2022+OR+repo%3Adankeyy%2Faoc22+OR+repo%3Adgkf%2Fadvent-of-code+OR+repo%3Aeissplitter%2Faoc-2022+OR+repo%3Aextorious%2Faoc2022+OR+repo%3Afelixr%2Fadvent-of-code+OR+repo%3Ajuriad%2Fadvent2022+OR+repo%3Ampizzzle%2FAdventOfCode+OR+repo%3Asaltysylvi%2Fbqn-aoc2022+OR+repo%3ARKBethke%2Faoc23-bqn+OR+repo%3Aazenna%2Fadvent-of-code-2023+OR+repo%3Aicendoan%2Faoc+OR+repo%3Aqqii%2Fadvent-of-code-2023+OR+repo%3Atimmarinin%2Faoc2023+OR+repo%3Adlozeve%2Faoc2023%29) of added files gives 286, while [this half](https://github.com/search?type=code&q=path%3A*.bqn+%28repo%3AAlexDikelsky%2Fpuzzles+OR+repo%3Aalephno%2Faoc2021+OR+repo%3Aalvinvoo%2Faoc2021+OR+repo%3Aarwn%2Faoc2021+OR+repo%3Adancek%2Fbqn-advent2021+OR+repo%3Afrasiyav%2FAoC2021+OR+repo%3Am-lima%2Fadvent-of-code-2021+OR+repo%3AAugustUnderground%2FAoC2022+OR+repo%3AChoram%2FAoC2022BQN+OR+repo%3ANhlest%2FAoC2022+OR+repo%3ASamuelSarle%2Fadvent+OR+repo%3Aakamayu-ouo%2FAoC+OR+repo%3Abddean%2Faoc%29) returns 150 and [this half](https://github.com/search?type=code&q=path%3A*.bqn+%28repo%3Adancek%2Fbqn-advent2022+OR+repo%3Adankeyy%2Faoc22+OR+repo%3Adgkf%2Fadvent-of-code+OR+repo%3Aeissplitter%2Faoc-2022+OR+repo%3Aextorious%2Faoc2022+OR+repo%3Afelixr%2Fadvent-of-code+OR+repo%3Ajuriad%2Fadvent2022+OR+repo%3Ampizzzle%2FAdventOfCode+OR+repo%3Asaltysylvi%2Fbqn-aoc2022+OR+repo%3ARKBethke%2Faoc23-bqn+OR+repo%3Aazenna%2Fadvent-of-code-2023+OR+repo%3Aicendoan%2Faoc+OR+repo%3Aqqii%2Fadvent-of-code-2023+OR+repo%3Atimmarinin%2Faoc2023+OR+repo%3Adlozeve%2Faoc2023%29) returns 157, totalling 307. And these "286" files were needed to increase BQN's total from 1.8k to 2k, as earlier 255 wasn't enough.

**Comment by lildude** [comment]
Popularity really isn't the priority right now... passing tests is 😉

**Comment by mlochbaum** [comment]
Apologies, I'd just talked to skykanin who believed popularity was the only remaining issue. I'm asking around to see if I can find someone to help.

**Comment by skykanin** [comment]
@lildude could you approve the workflow? I was able to get rid of all the test failures locally :slightly_smiling_face:

**Comment by skykanin** [comment]
@lildude Github's search indexing now shows that BQN has [3.4k](https://github.com/search?q=NOT+is%3Afork+path%3A*.bqn&type=code) unique files so I think this PR should be good to merge after the tests are rerun.

**Comment by skykanin** [comment]
@lildude Github's search indexing now shows that BQN has [3.4k](https://github.com/search?q=NOT+is%3Afork+path%3A*.bqn&type=code) unique files so I think this PR should be good to merge after the tests are rerun.

**Review by lildude — APPROVED** [review]

**Pull request merged**
