### PR TITLE
Add Spicelang language

### PR DESCRIPTION
**Pull request by marcauberer**
## Description
Add support for the Spice programming language

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension: [search results](https://github.com/search?q=extension%3Aspice+f+as+ext+NOT+nothack)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s): [sample source](https://github.com/spicelang/linguist/blob/master/samples/Spice/sample.spice)
    - Sample license(s): MIT
  - [x] I have included a syntax highlighting grammar: [lightshow demo](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fspicelang%2Fvscode-spice%2Fmain%2Fsyntaxes%2Fspice.tmLanguage.xml&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fspicelang%2Flinguist%2Fmaster%2Fsamples%2FSpice%2Fsample.spice&code=)
  - [ ] <s>I have updated the heuristics to distinguish my language from others using the same extension.</s>

### CODE REVIEW

**Comment by Alhadis** [comment]
SPICE is also the name of a [well-known](https://en.wikipedia.org/wiki/SPICE) circuit simulation program, which uses a [plain-text file format](https://www.cpp.edu/~prnelson/courses/ece220/220-spice-notes.pdf) to represent models and schematics. I therefore suspect most of the [~1,306 search results for `.spice`](https://github.com/search?q=extension%3Aspice+f+as+ext+NOT+nothack) are actually circuit-board schematics, especially since there are literally only [9 people](https://github.com/spicelang/spice/stargazers) who've starred your project (suggesting that it falls well short of Linguist's popularity criteria).

**Comment by z0gSh1u** [comment]
Instead of this [Spice Lang](https://github.com/spicelang/spice), I'd like [SPICE](https://en.wikipedia.org/wiki/SPICE), the circuit simulation language, to be recognized by GitHub. Its external name is `.sp`, which is now recognized as `SourcePawn`.

SPICE is widely used in Transistor-Level Circuit Design and VLSI. Just search `SPICE` or `HSPICE` with language `SourcePawn`, there are many SPICE programs.

See:
https://github.com/search?l=SourcePawn&p=1&q=SPICE&type=Repositories
https://github.com/search?l=SourcePawn&p=1&q=HSPICE&type=Repositories

**Comment by lildude** [comment]
@z0gSh1u please open a [new issue](https://github.com/github/linguist/issues/new?assignees=&labels=Add+Language%2C+Good+First+Issue&template=new_language.md&title=) or submit a PR youself to add support.

**Comment by lildude** [comment]
I'm closing this PR as usage really hasn't grown anywhere near our usage requirements in the two years this PR has been open. 

Please feel free to open a new PR once usage meets our requirements.

**Pull request closed without merging**
