### PR TITLE
Add `rust-script` to Rust interpreters

### PR DESCRIPTION
**Pull request by fornwall**
Detect [rust-script](https://rust-script.org/) files as rust source code.

## Description
Detect files using the [rust-script](https://rust-script.org/) interpreter as Rust source code. Asked for [here](https://github.com/fornwall/rust-script/issues/87). See [this GitHub search](https://github.com/search?q=%22%2Fusr%2Fbin%2Fenv+rust-script%22&type=code) for examples of usage.

## Checklist:

- [x] **I am adding new or changing current functionality**
  
  - [x] I have added or updated the tests for the new or changed functionality.

### CODE REVIEW

**Review by Alhadis — CHANGES_REQUESTED** [review]
Could you please provide a source for the sample you've included? We need to be sure that it's been released under an open-source license.

**Comment by fornwall** [comment]
> Could you please provide a source for the sample you've included? We need to be sure that it's been released under an open-source license.

It was just a personal utility script of mine, which I hereby license under the MIT license.

@Alhadis Is that good enough, or would you rather prefer to pick a script from an existing repository?

**Comment by Alhadis** [comment]
> It was just a personal utility script of mine, which I hereby license under the MIT license.

That's perfectly fine. Just wanted to get that on record. 👍

**Review by Alhadis — APPROVED** [review]

**Review by lildude — APPROVED** [review]
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Review by lildude — APPROVED** [review]

**Pull request merged**
