### PR TITLE
Add `uv.lock` as a TOML file

### PR DESCRIPTION
**Pull request by edgarrmondragon**
## Description

> `uv.lock` is a human-readable TOML file but is managed by uv and should not be edited manually.

https://docs.astral.sh/uv/concepts/projects/#lockfile

## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3Auv.lock
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/edgarrmondragon/uv-click-example/blob/ce8dbff4f7b16e50b159b0cb46b00bd2ee8357b3/uv.lock
    - Sample license(s): MIT
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Your sample is being surpressed by the diff because of its size which means it's too big for us. Please replace it with a smaller real-world sample.

**Comment by edgarrmondragon** [comment]
> Your sample is being surpressed by the diff because of its size which means it's too big for us. Please replace it with a smaller real-world sample.

Done! 99b49baf54ebcc95c2b130a051305c839bc385a6

**Comment by edgarrmondragon** [comment]
FWIW regarding https://github.com/github-linguist/linguist/labels/Pending%20Popularity, there were ~150 repos with a `uv.lock` file in search results this morning and we're at 183 now, so it's safe to assume the ecosystem will quickly reach the "hundreds of repositories" threshold.

**Review by lildude — APPROVED** [review]
Wow! A jump of several hundred in a week. Nice.

**Pull request merged**
