### PR TITLE
Fix trailing whitespace & empty lines

### PR DESCRIPTION
**Pull request by michidk**
Fix trailing whitespace & empty lines in various files

### CODE REVIEW

**Comment by Alberto8657** [comment]
michidk:fix-f

**Comment by michidk** [comment]
Hey @lildude, is there anything blocking this from getting merged?

**Comment by lildude** [comment]
> Hey @lildude, is there anything blocking this from getting merged?

Not really, but as it's not actually making any real changes, I've not given it any priority and won't until I have the time, which may only be when I'm preparing the next release.

**Review by lildude — APPROVED** [review]
ProTip: these kinds of PRs are often not taken very kindly by many projects which don't use space-sensitive languages, especially as it was a common tactic used to game Hacktoberfest. In future, I encourage you to include real useful code changes along with whitespace changes, but if you must do just a whitespace PR, certainly don't chase it up 😉

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Comment by michidk** [comment]
I separated this PR by intent since it concerns multiple files and makes it easier to review that when mashed together with my other PR. The reason why I made this PR is that I had a auto formatter running in my IDE when developing my other PR, and I always had to make sure to not to commit the format changes that did not concern my code, which was quite annoying.
I like to keep my PRs on topic only and think that putting changes that are not related to the actual PR in the same one is bad practice.

**Review by lildude — APPROVED** [review]

**Pull request merged**
