### PR TITLE
Add support for Pkl

### LINKED ISSUE #6705: New Language: Pkl
## Language name

Pkl

## URL of example repository

https://github.com/apple/pkl-k8s-examples

## URL of syntax highlighting grammar

https://github.com/apple/tree-sitter-pkl

## Most popular extensions

- [VSCode](https://github.com/apple/pkl-vscode)
- [Neovim](https://github.com/apple/pkl-neovim)
- [IntelliJ](https://github.com/apple/pkl-intellij)

## Detected language

none

### PR DESCRIPTION
**Pull request by sgammon**
Adds support for the new [Pkl](https://pkl-lang.org/index.html) configuration language from Apple.

## Description

Credit to:
- @darvld and myself from the Elide team for assembling the tests + linguist changes
- @nishtahir for the textmate grammar
- @pixelcmtd for the feature request issue at #6705 

Fixes and closes #6705 
Fixes and closes apple/pkl#155

### Changelog

- feat: language support for Apple Pkl with textmate bundle
- feat: heuristics to distinguish with Python Pickle
- test: tests/samples for Apple Pkl configuration language

## Checklist:

- [ ] **I am adding a new extension to a language.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.pkl
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  [Here](https://github.com/search?type=repositories&q=NOT+is%3Afork+path%3A*.pkl+KEYWORDS), but it is hard to distinguish Pkl sources from Pickle (Python) data
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - Samples from the official [`apple/pkl-go-examples`](https://github.com/apple/pkl-go-examples)
    - Sample license(s): [Apache 2.0](https://github.com/apple/pkl-go-examples?tab=Apache-2.0-1-ov-file#readme)
  - [x] I have included a syntax highlighting grammar: [Grammar here](https://github.com/nishtahir/language-pkl)
      
  - [x] I have added a color
    - Hex value: `#6b9543`
    - Rationale: Main color (outer gear green) used in the [Pkl project icon](https://github.com/apple/pkl/pull/212)
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
See inline comments.

Also:

> [Here](https://github.com/search?type=repositories&q=NOT+is%3Afork+path%3A*.pkl+KEYWORDS), but it is hard to distinguish Pkl sources from Pickle (Python) data

Search accepts [regexes](https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#using-regular-expressions) now so you can use your heuristic to confirm popularity.

**Comment by lildude** [comment]
Oh yes, and we're going to also need a test for the heuristic.

**Comment by stackoverflow** [comment]
Hi @sgammon. We're preparing a PR for linguist, it should come soon. The grammar you are using in this submission is our current vscode one, which is pretty bare bones, we have a updated version of it now.

**Comment by sgammon** [comment]
@stackoverflow Ah, good to know 😄. We can close this PR or point at the new grammar, entirely up to you guys.

**Pull request closed without merging**
