### PR TITLE
This Pull Request adds support for PunkScript in Linguist, including usage examples.

### PR DESCRIPTION
**Pull request by AndersonShelby**
## Checklist:

- [ ] **I am adding a new extension to a language.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
    - 
    - Sample license(s):
  - [x] I have included a syntax highlighting grammar: https://github.com/AndersonShelby/PunkScript/blob/master/punkscript.abnf
      
  - [x] I have added a color
    - Hex value: `#0080FF`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please follow the instructions in the CONTRIBUTING.md file and translate all text into English.

**Comment by AndersonShelby** [comment]
Okay, I've translated all the texts including comments in scripts. Is there anything else to check?

**Comment by lildude** [comment]
> Okay, I've translated all the texts including comments in scripts. Is there anything else to check?

Yup. 

1. Follow all of the instructions in CONTRIBUTING.md for adding a new language (you've missed a few)
2. Actually add the TextMate compatible grammar if you want syntax highlighting
3. Complete filling in the PR template

That said on further investigation, this appears to be a very new language with absolutely zero references to it on GitHub or even Google. I see you've referenced a private repo which suggests this might be a hobby project. We have usage requirements for adding a new language which means we don't add support for very new and hobby languages. Accordingly I'm closing this PR. Feel free to create a new PR once your language meets our usage requirements.

**Comment by AndersonShelby** [comment]
Okay, I'll do that.

**Pull request closed without merging**
