### PR TITLE
Added Modu support

### PR DESCRIPTION
**Pull request by aquiffoo**
## Description
In December 2024, Cyteon created the Modu programming language, that aims to be readable and fast, even tho it's interpreted. I like the project, so i decided to add support for it in GitHub's linguist. The project is improving every day, it's criminally underrated!

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.modu
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - samples/Modu/helloworld.modu (shows a simple function declaration and hello world)
      - samples/Modu/math.modu (showcases if statements and library imports
    - Sample license(s):
  - [x] I have included a syntax highlighting grammar
  - [x] I have added a color
    - Hex value: `#F5AAAA`
    - Rationale: The color was picked on Modu's logo, available in https://cyteon.tech/modu
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by coolbeans1212** [comment]
modu is awesome, must add

**Comment by lildude** [comment]
> In December 2024

There is absolutely no chance this will meet our usage requirements in 29 days of existence… I'm not even going to check. We do not add support for very new or hobby languages. 

As such, I'm closing this PR. Feel free to open a new PR when the language meets our usage requirements, and be sure to follow the instructions in the CONTRIBUTING.md file when you do.

**Comment by coolbeans1212** [comment]
>:(

**Comment by computerblade-official** [comment]
Tbh I agree with @lildude. It's too early to add support for this language right now.

**Comment by 404PageN0tFound** [comment]
ADD SUPPORT

**Pull request closed without merging**
