### PR TITLE
Release v7.28.0

### PR DESCRIPTION
**Pull request by lildude**
Time for a new release.

- [ ] Gem pushed to RubyGems & GitHub Package Registry
- [ ] Deployed to GitHub.com
- [ ] Grammars deployed to Syntax highlighting service - highlighting won't be 💯 up-to-date until this happens

I'm aiming to make and deploy this release by EoD 12 Dec 2023.

NOTE: Search results will not reflect changes and new lanuguages until the upstream [go-enry](https://github.com/go-enry/go-enry) library is updated to pull in the changes from this release and that then deployed to GitHub's Search.

### CODE REVIEW

**Review by Alhadis — APPROVED** [review]
I'm sorry for my absence lately. 😞 Real life's gotten between me and GitHub, so I've fallen behind with reviewing PRs and stuff…

**Comment by lildude** [comment]
NP @Alhadis Your real life and wellbeing is the most important thing. Look after yourself.

**Comment by lildude** [comment]
Hit a [snag](https://github.com/github-linguist/linguist/pull/6603#issuecomment-1852349261) with the syntax highlighter so the deploy to GitHub and the syntax highlighter will take place tomorrow morning 🇬🇧 time.

**Comment by jtbandes** [comment]
@lildude FYI, a Swift team member reported [a small bug](https://github.com/jtbandes/swift-tmlanguage/issues/5) with the grammar – it would be awesome to include the fix (now merged to main) with tomorrow's release if possible!

**Comment by lildude** [comment]
Sorry, it's too late. The release has been made, just not deployed. This will have to wait until the next release.

**Comment by lildude** [comment]
We're now live everywhere.

**Pull request merged**
