### PR TITLE
Release v7.30.0

### PR DESCRIPTION
**Pull request by lildude**
Time for a new release.

- [ ] Gem pushed to RubyGems & GitHub Package Registry
- [ ] Deployed to GitHub.com
- [ ] Grammars deployed to Syntax highlighting service - highlighting won't be 💯 up-to-date until this happens

I'm aiming to make and deploy this release by 11 June 2024.

NOTE: Search results will not reflect changes and new lanuguages until the upstream [go-enry](https://github.com/go-enry/go-enry) library is updated to pull in the changes from this release and that then deployed to GitHub's Search.

### CODE REVIEW

**Comment by lildude** [comment]
This release is now live everywhere on GitHub.

**Comment by 319684023** [comment]
fuck you all bitch

> `**[1000000364.PDF](https://github.com/user-attachments/files/319684023

**Comment by 319684023** [comment]
> fuck you all bitch
> 
> > `**[1000000364.PDF](https://github.com/user-attachments/files/319684023

https://console.cloud.google.com/storage/browser?_ga=2.163330044.1757235848.1718327825-2087181310.1718327807&project=windy-impact-426014-u2&prefix=&forceOnBucketsSortingFiltering=true

**Comment by 319684023** [comment]
19184-280x210
@319684023 this is fucking disgusting. like ive said. ill die single and alone

**Pull request merged**
