### PR TITLE
Add Roc Language

### PR DESCRIPTION
**Pull request by ryanb**
This adds syntax grammar for [Roc](https://www.roc-lang.org), an up and coming functional language.

@lildude It would be amazing to get this in before 7.28.0 is deployed tomorrow. A lot of us are doing Advent of Code with Roc this year and would really appreciate some syntax highlighting.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.roc+app
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [ParserString.roc](https://github.com/ryanb/linguist/blob/roc/samples/Roc/ParserString.roc)
      - [PgCmd.roc](https://github.com/ryanb/linguist/blob/roc/samples/Roc/PgCmd.roc)
      - [PgProtocolBackend.roc](https://github.com/ryanb/linguist/blob/roc/samples/Roc/PgProtocolBackend.roc)
      - [PgSchema.roc](https://github.com/ryanb/linguist/blob/roc/samples/Roc/PgSchema.roc)
    - Sample license(s):
      - They are all [Universal Permissive License](https://opensource.org/license/upl/)
  - [x] I have included a syntax highlighting grammar: https://github.com/ivan-demchenko/roc-vscode-unofficial
    - Even though this repo says "unofficial", it was [requested to be used](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Syntax.20Highlighting.20on.20GitHub/near/407334934) by Richard Feldman, the creator of Roc.
  - [x] I have added a color
    - Hex value: `#7c38f5`
    - Rationale: Primary color on https://roc-lang.org
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
If you can get this in by 11am UTC, it'll make it, but we really need real-world usage samples. These are contrived examples from the language creator, not real-world examples of in-the-wild real usage.

**Comment by ryanb** [comment]
@lildude I updated the samples with real-world code and rebased off master. Let me know if you need anything else.

**Review by lildude — CHANGES_REQUESTED** [review]
Now I'm going to go the other way and ask you to please replace the large samples (those suppressed in the diff by default) with smaller ones 😁

**Comment by ryanb** [comment]
@lildude do the samples need to be complete and compile on their own, or can they be snippets of a larger file?

**Comment by lildude** [comment]
They need to be real world examples… we want samples that demonstrate how people really use the language, not contrived hogwash. We don't care if they compile or not as all we're doing is using them to train the classified.

**Review by lildude — CHANGES_REQUESTED** [review]
Your tests are failing because you've got samples in a sub-directory of the `Roc` directory. All samples must be directly in the language named directory.

**Comment by ryanb** [comment]
@lildude I updated the samples to match the requirements. Let me know if there are any other issues.

**Comment by faldor20** [comment]
@ryanb @lildude  Would it be better to use a tree-sitter grammar? This one is complete and i suspect would provide better highlighting than a textmate style one: https://github.com/faldor20/tree-sitter-roc

**Comment by lildude** [comment]
> @ryanb @lildude Would it be better to use a tree-sitter grammar? This one is complete and i suspect would provide better highlighting than a textmate style one: https://github.com/faldor20/tree-sitter-roc

Nope as linguist has no control over the use of tree-sitter grammars as this is entirely up to the team that maintains the highlighting engine as mentioned previously in https://github.com/github-linguist/linguist/discussions/6073. As with the same question in https://github.com/github-linguist/linguist/pull/6689#issuecomment-1913086778 this is not likely to happen any time soon given the low usage of this language.

**Comment by faldor20** [comment]
Ahh, thanks for clarifying, that's a shame. I'll raise this again sometime in the next decade if roc achieves some level of success 😅

**Comment by ryanb** [comment]
@lildude any update on the status of this? Do you need anything else from me?

**Review by lildude — APPROVED** [review]
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Comment by ryanb** [comment]
Thanks for merging! Looking forward to seeing it live.

**Pull request merged**
