### PR TITLE
Add Edge Language

### PR DESCRIPTION
**Pull request by evoactivity**
Adds the edge templating language used by AdonisJS
https://edgejs.dev/

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=(path%3A*.edge)+AND+(content%3A%40section+OR+content%3A%40if+OR+content%3A%40end+OR+content%3A%3Cdiv%3E)+NOT+is%3Afork&type=code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/adocasts/adocasts/blob/a8be4869db1355f77f2280744e50741b0e2aa694/resources/views/pages/pricing.edge
    - Sample license(s): https://github.com/adocasts/adocasts/blob/main/LICENSE
  - [x] I have included a syntax highlighting grammar: https://github.com/edge-js/edge-vscode
      
  - [x] I have added a color
    - Hex value: `#0dffe0`
    - Rationale: Color used in official Edge logo found on https://edgejs.dev
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by evoactivity** [comment]
One question I have is the grammar includes `source.js#expression` which is not available in the atom javascript textmate grammar, but is available in the microsoft grammar. I think GitHub uses the treesitter grammar for javascript, but I assume it will use the textmate grammar when being included by another textmate grammar. Can you confirm if my assumption is correct about using the textmate grammar when included by other textmate grammars, and if so which version of the grammar is in use.

@thetutlage If the atom grammar is being used I'd recommend updating the edge grammar to include `source.ts#expression` instead.

**Comment by lildude** [comment]
> I think GitHub uses the treesitter grammar for javascript, 

Correct a denoted by the 🐌 in the list of grammers [README.md](https://github.com/github-linguist/linguist/blob/master/vendor/README.md)

> but I assume it will use the textmate grammar when being included by another textmate grammar. Can you confirm if my assumption is correct about using the textmate grammar when included by another textmate grammars, 

It is.

> and if so which version of the grammar is in use.

The latest SHA of the repo the [submodule points to.](https://github.com/github-linguist/linguist/blob/559a6426942abcae16b6d6b328147476432bf6cb/.gitmodules#L673)

**Comment by evoactivity** [comment]
Thanks for the confirmations @lildude 

I've made the required updates to the edge grammar, so everything _should_ be fine from our end now. I've tested the updated grammar with nova lightshow and all seems to be working great :)

**Review by lildude — CHANGES_REQUESTED** [review]
Looking good, just one request: please change the sample for a real-real world sample; this appears to be a "Hello World" type example.

**Comment by evoactivity** [comment]
Done 🙂

**Review by lildude — APPROVED** [review]
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Pull request merged**
