### PR TITLE
chore: migrate vscode-vba-json to bait-lang

### PR DESCRIPTION
**Pull request by serkonda7**
## Description
I have transfered the vscode-vba-json repo and update all the references/submodule here

## Checklist:

- [ ] **I am adding a new extension to a language.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [ ] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/tiabeast/vscode-vba-json
  - New:https://github.com/bait-lang/vscode-vba-json

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

### CODE REVIEW

**Comment by lildude** [comment]
🤔 why not just use the grammar you directly maintain?

**Comment by serkonda7** [comment]
> 🤔 why not just use the grammar you maintain directly?

Because it's written in yaml which is not supported by linguist

**Comment by lildude** [comment]
> Because it's written in yaml which is not supported by linguist

I'm not sure why you think this. Yaml is definitely supported, as is xml (plist) and cson. Many grammars use yaml without issues. The compiler converts all grammars to json so you don't need to 🙂

**Comment by serkonda7** [comment]
Might have overlooked it when originally adding it. Will make a new PR.

**Pull request closed without merging**
