### PR TITLE
Add OMNeT++ NED language

### PR DESCRIPTION
**Pull request by adamgeorge309**
This adds the OMNeT++ NED language.

## Description
NED (extension .ned) is a DSL for the OMNeT++ network simulator. It is used by model frameworks for OMNeT++, such as the INET framework, Simu5G, Veins, etc. We are the team that develops [OMNeT++](https://github.com/omnetpp/omnetpp) and the [INET Framework](https://github.com/inet-framework/) and we have created a TextMate grammar for this language.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.ned+package
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/inet-framework/inet
    - Sample license(s):
      - LGPLv3
  - [x] I have included a syntax highlighting grammar: https://github.com/omnetpp/omnetpp-textmate-ned
      
  - [x] I have added a color
    - Hex value: `#08607c`
    - Rationale: Matches the branding guidelines for the OMNeT++ project.
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
This PR is missing the cached licence file from the grammar which should have been created when you ran `script/add-grammar`:

https://github.com/github-linguist/linguist/blob/ebbedf06dc18e929104a4a3573ac43b43298a761/script/add-grammar#L135

Please add this file.

**Comment by lildude** [comment]
Please merge main into your branch again as I can't approve CI to run without the latest changes.

**Comment by adamgeorge309** [comment]
Merged. Thanks

**Review by lildude — APPROVED** [review]
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Pull request merged**
