### PR TITLE
Add `.swcrc` to "JSON with Comments"

### PR DESCRIPTION
**Pull request by g-plane**
## Description

Mark ".swcrc" as "JSON with Comments".

## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      - https://github.com/search?q=path%3A**%2F.swcrc%20NOT%20nothack&type=code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s): Sample taken from the default config at https://github.com/swc-project/swc-playground/blob/main/src/state.ts#L69-L91
    - Sample license(s): MIT
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
> I have included a real-world usage sample for all extensions added in this PR:
> 
>   * Sample source(s): https://github.com/g-plane/linguist/blob/swcrc/samples/JSON%20with%20Comments/filenames/.swcrc

Please update this to link to the actual source of this file, not your fork of this repo. We also need to know the license of the sample file (you accidentally deleted the "Sample license(s):" line for this).

**Comment by g-plane** [comment]
I copied from [SWC playground default config](https://github.com/swc-project/swc-playground/blob/main/src/state.ts#L69-L91) with some modification, not an actual file. Is it OK?

**Comment by lildude** [comment]
Ok. That's fine. I've updated the OP to reflect this.

**Review by lildude — APPROVED** [review]

**Comment by lildude** [comment]
Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details. 

We've just made a release last week so the next one won't be for a few months.

**Review by lildude — APPROVED** [review]

**Pull request merged**
