### PR TITLE
Add pnpm lockfiles as generated

### PR DESCRIPTION
**Pull request by SuperchupuDev**
## Description

Currently, npm lockfiles (`package-lock.json`) are considered generated files. pnpm lockfiles weren't marked as generated, even though they are indeed generated files

## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3Apnpm-lock.yaml
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/biomejs/biome/blob/2355969cbc1f4e83872410c8f48f9569213ad1c8/pnpm-lock.yaml
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
Let me know if I need to change anything, this is my first PR to this repo

**Comment by SuperchupuDev** [comment]
I see it was decided in #4348 not to mark yarn lockfiles as generated. Would pnpm lockfiles fall under the same boat? If not, why are npm lockfiles marked as generated but not these ones?

**Comment by SuperchupuDev** [comment]
> Yes, remove the yarn lock related change. You'll also need to add tests and a sample. See https://github.com/github-linguist/linguist/pull/6748 as an example where a file has recently been marked as generated.
Done. I tried to find a small sample of a pnpm lockfile but this 9k line one was the smallest I could find for a relevant enough project. I hope that's not much of a problem

**Comment by lildude** [comment]
> I hope that's not much of a problem

It is… hooooge. Please find a smaller one. We don't need a real world file for test fixtures so feel free to write a small representative one by hand if you can't find a smaller one.

**Review by lildude — APPROVED** [review]

**Pull request merged**
