### PR TITLE
Added PhpSlides extension

### PR DESCRIPTION
**Pull request by dconco**
## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.psl+psl
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.view.php+phpslides
  - [X] I have included a real-world usage sample for all extensions added in this PR.

- [X] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.psl+psl
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.view.php+phpslides
  - [X] I have included a real-world usage sample for all extensions added in this PR.
  - [X] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [X] I have added a color
    - Hex value: `#6432C9`
    - Rationale: 
  - [X] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by belloibrahim2** [comment]
Great work 👍 at least we can now know when coding PhpSlides 🙏

**Comment by abrahamdominic** [comment]
Adding PhpSlides language extension enhances code readability, discoverability, and organization. 

Approve to support the growing PhpSlides ecosystem

**Review by lildude — CHANGES_REQUESTED** [review]
PhpSlides is a framework. We do not add support for frameworks. The files you've added look like valid PHP so if anything, the only thing that can be done is to add the relevant extensions to the current PHP entry, iff they meet our usage requirements. From a quick search, neither are anywhere close to meeting our usage requests and as such, I'm closing this PR.  

Feel free to open a new PR to add the `.psl` extension to PHP when it meets our requirements. Users can use an override until then. The `.view.php` should also be correctly identified as PHP.

**Comment by kollydap** [comment]
dding a language extension for PhpSlides to GitHub's linguist library would significantly improve code visibility and project identification. This enhancement allows developers to see "PhpSlides" in the languages used when projects are pushed, making it easier to recognize PhpSlides-specific repositories at a glance. This would provide clarity and visibility to the growing PhpSlides community, ensuring that PhpSlides code is correctly attributed and identified on GitHub.

**Comment by lildude** [comment]
Developers will never see PhpSlides in the language stats as it is a framework and as stated previously, we don't add frameworks as they are not programming languages. That is why you'll never see Ruby on Rails or Laravel in the language stats. Instead you'll see Ruby and PHP respectively.

**Comment by dconco** [comment]
Blade was there, .blade, .blade.php as it is laravel framework for view. Well as you've said earlier that is not not used by many developers, I wouldn't complain about that. We'll try our best to improve PhpSlides and it's features.

**Pull request closed without merging**
