### PR TITLE
Change grammar source for Genero language and rename

### PR DESCRIPTION
**Pull request by sebflaesch**
## Description
For .4gl and .per files, using vendor's official repository for syntax highlighting: FourjsGenero/GeneroFgl.tmbundle

## Checklist:
- [X] **I am renaming the language name(s)**
  - "Genero" => "Genero 4gl"
  - "Genero Forms" => "Genero per"
  - This is to fit with the names we use in our VSCode extension.

- [X] **I am removing existing samples**
  - Existing samples are not state of the art Genero programming: Keywords should be uppercase.

- [X] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/alienriver49/genero.tmbundle
  - New: https://github.com/FourjsGenero/GeneroFgl.tmbundle

### CODE REVIEW

**Comment by lildude** [comment]
Please update the template explaining why you are removing the original samples. As mentioned [before](https://github.com/github-linguist/linguist/issues/6628#issuecomment-1845605744), we only remove samples if they're blatantly wrong such that they're either complete rubbish, are useless "Hello world" types or are for a completely different language as these all affect the classifier. The code samples don't have to work in isolation, they just need to be real world samples people have actually used as some point.

**Comment by lildude** [comment]
Oh yes, and add an explanation for the renames too please. This helps users who notice the change understand why it has happened when they find this PR.

**Review by lildude — CHANGES_REQUESTED** [review]
Looks like the license file from the grammar wasn't cached or you forgot to commit it.

If you can't find the changed file, please run this command to download it and then add it to this PR:

https://github.com/github-linguist/linguist/blob/6a9a3e413a0b07d4560978a98da0bd4d68ee1f77/script/add-grammar#L134

**Comment by sebflaesch** [comment]
Oh...
It's my first PR so I will have to learn about how to update a PR.
The command for the license did not game me any comment.
Is the required file something like
vendor/licenses/git_submodule/GeneroFgl.tmbundle.dep.yml
?

I do not know how to update the PR, should I just commit / push new changes in my fork/branch and ref to it here?
Pffffff......

I do not know how to update the template of the PR.

**Comment by sebflaesch** [comment]
BTW we are the software vendor of Genero 4gl/per so about samples removable, please trust us, and consider the existing samples as "blatantly wrong such that they're either complete rubbish".

**Comment by lildude** [comment]
I see you've found the file and worked out how to add it to the PR (commit to your fork and push and it updates the PR).

Regarding:

> * This is to fit with the names we use in our VSCode extension.

Is this how users and the company refer to the names of the languages in discussions, usage etc? I ask as this is what appears on the sidebar on repos and in the search results and most companies prefer the official names of the languages to be reflected and users also prefer the names they generally use.

**Review by lildude — APPROVED** [review]
Great! Thanks for all the explanations etc. Looks good to me now. I aim to make a release tomorrow morning https://github.com/github-linguist/linguist/pull/6627 and this will be included.

**Comment by lildude** [comment]
Oooof:

```console
➜ rm Gemfile.lock && script/bootstrap
==> Initialising submodules…
Error updating vendor/grammars/GeneroFgl.tmbundle
fatal: remote error: upload-pack: not our ref 08c18d5226822a1ebdc21d3f8454a12c19e080ae
fatal: Fetched in submodule path 'vendor/grammars/GeneroFgl.tmbundle', but it did not contain 08c18d5226822a1ebdc21d3f8454a12c19e080ae. Direct fetching of that commit failed.
Submodule path 'vendor/grammars/syntax': checked out 'ced984baed78a85834dbbd1724d3e600ba50ef8d'
✘ git st
## feature/Terraform-templates
 M script/bootstrap
 M vendor/grammars/GeneroFgl.tmbundle
➜ git submodule update --init -- vendor/grammars/GeneroFgl.tmbundle/
fatal: remote error: upload-pack: not our ref 08c18d5226822a1ebdc21d3f8454a12c19e080ae
fatal: Fetched in submodule path 'vendor/grammars/GeneroFgl.tmbundle', but it did not contain 08c18d5226822a1ebdc21d3f8454a12c19e080ae. Direct fetching of that commit failed.
✘
```

I'll see if I can fix this as part of the new release.

**Comment by lildude** [comment]
Ignore ☝️ I think it might have been something with the branch which had some other odd things going on. Things are looking good on master.

**Comment by lildude** [comment]
Yes, I need to make a release and deploy it to GitHub.com. I briefly document the steps in the release PR, in this case https://github.com/github-linguist/linguist/pull/6627, which I check off as each happens.

I've hit a bit of a snag with the syntax highlighter which needs the service owners to look in to (they're all in the US) so there's going to be a delay to the next steps.

**Pull request merged**
