### PR TITLE
PLI language

### PR DESCRIPTION
**Pull request by henriqueromera**
Adding pli language to support bunch of mainframe modernisation projects around the world.

## Checklist:

- [X] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [X] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [X] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [X] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Review by lildude — CHANGES_REQUESTED** [review]
Please follow the instructions in the CONTRIBUTING.md file and fill in the appropriate section of the PR template/

**Comment by henriqueromera** [comment]
PLI is mostly used in companies and repos are private, like the company I work, so I cant provide any repo sample.

**Comment by lildude** [comment]
> PLI is mostly used in companies and repos are private, like the company I work, so I cant provide any repo sample.

We rely solely on public usage as this is the only way we can measure usage. A quick search of the extensions suggests you might not have tried to determine popularity of the extensions as there is quite a lot of usage so you can definitely finish this PR as documented and it will be considered if or when usage of all extensions are met.

Unless you can come up with a very accurate heuristic, I'd recommend you remove `.inc` as this is a very generic extension.

**Comment by lildude** [comment]
Closing as request to follow correct procedure has not been actioned in nearly 5 months.

**Pull request closed without merging**
