### PR TITLE
Add Glimmer TS language

### PR DESCRIPTION
**Pull request by gilest**
## Description
Adds support for TypeScript-flavoured [Glimmer.js](https://glimmerjs.com/) which will be the [component authoring format](https://github.com/ember-template-imports/ember-template-imports) of the [next Edition of Ember.js](https://emberjs.com/editions/polaris/).

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - [.gts search](https://github.com/search?q=%28path%3A*.gts%29+AND+%28content%3A%3Ctemplate%3E+OR+content%3A%40glimmer+OR+content%3A%40ember%29+NOT+is%3Afork&type=code) 2k files excluding forks
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
	    - [class.gts](https://github.com/cardstack/cardstack/blob/main/packages/boxel/addon/components/boxel/input/time/usage.gts)
	    - [template-only.gts](https://github.com/EmberCrate/website/blob/main/app/components/resource-card.gts)
    - Sample license(s):
	    - class.gts -(https://github.com/cardstack/cardstack) MIT
	    - template-only.gjs (https://github.com/CrowdStrike/opensource.crowdstrike.com) MIT
  - [x] I have added a color
    - Hex value: `#3178c6`
    - Rationale: TypeScript colour which is also used by TypeScript and TSX
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by gilest** [comment]
CI is failing because the [vscode-vba repo](https://github.com/tiabeast/vscode-vba-json) has been removed from GitHub

**Comment by lildude** [comment]
All should be good now I've merged https://github.com/github-linguist/linguist/pull/6678

**Comment by deanylev** [comment]
Is this able to be merged? Reviewing our gts files in PRs is a nightmare at the moment 🙏

**Comment by Techn1x** [comment]
Looking forward to this as well. For what it's worth, we have 300+ GTS files in a private repo.

**Review by lildude — APPROVED** [review]
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Pull request merged**
