### PR TITLE
Add Toit language

### PR DESCRIPTION
**Pull request by floitsch**
Adds the Toit language.

## Description
Toit (toitlang.org) is a general purpose language that has been designed to also run well on embedded devices like the ESP32.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?q=path%3A*.toit+AND+NOT+%28user%3Atoitlang+OR+user%3Atoitware+OR+user%3Afloitsch+OR+user%3Adsobotta+OR+user%3Amikkeldamsgaard%29&type=code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/floitsch/toit-chatbot/blob/main/src/chatbot.toit
      - https://github.com/floitsch/log-uploader/blob/main/main.toit
      - https://github.com/toitware/toit-1-wire/blob/main/examples/family.toit
    - Sample license(s):
      - MIT (chatbot.toit and logger.toit)
      - BSD0 (one_wire.toit)
  - [x] I have included a syntax highlighting grammar: https://github.com/toitware/ide-tools
      
  - [x] I have added a color
    - Hex value: `#c2c9fb`
    - Rationale: This is one of the colors that is used in the color scheme of the toit.io page

### CODE REVIEW

**Comment by floitsch** [comment]
The repository that contains the syntax files is called "ide-tools", since it also contains files for other syntax highlighters (like VIM and codemirror).

I can definitely rename it, so it has "toit" in its name.
If preferred I can also move the tm files into a separate repository so that linguist doesn't pull down the codemirror and vim files.

**Comment by lildude** [comment]
> I can definitely rename it, so it has "toit" in its name.
> If preferred I can also move the tm files into a separate repository so that linguist doesn't pull down the codemirror and vim files.

No need. Things are fine as they stand.

I've marked this as pending popularity as there are only 70 files when we [exclude forks](https://github.com/search?q=path%3A*.toit+AND+NOT+%28user%3Atoitlang+OR+user%3Atoitware+OR+user%3Afloitsch+OR+user%3Adsobotta+OR+user%3Amikkeldamsgaard+OR+is%3Afork%29&type=code) (almost all of them are forks of repos owned by users you've excluded) from your search query.

**Comment by floitsch** [comment]
It might not be enough, but the Github search clearly is missing files.
Just looking through Toit's package manager I can see repositories with files in them that the search doesn't seem to see.

For example:
- https://github.com/davidlao2k/aht20-driver
- https://github.com/justind000/BH1750_Toit_driver/tree/main/src
- https://github.com/nilwes/bme680
- https://github.com/harshkc03/bmp280-driver
- https://github.com/Molbeck/GPIOMessaging
- https://github.com/lask/toit-hc-sr04

**Review by lildude — APPROVED** [review]

**Comment by Pea1594** [comment]
> Adds the Toit language.
> 
> ## Description
> Toit (toitlang.org) is a general purpose language that has been designed to also run well on embedded devices like the ESP32.
> 
> ## Checklist:
> 
> 
> 
> 
> - [x] **I am adding a new language.**
>   - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
>     - Search results for each extension:
>       
>       -  https://github.com/search?q=path%3A*.toit+AND+NOT+%28user%3Atoitlang+OR+user%3Atoitware+OR+user%3Afloitsch+OR+user%3Adsobotta+OR+user%3Amikkeldamsgaard%29&type=code
>   - [x] I have included a real-world usage sample for all extensions added in this PR:
>     - Sample source(s):
>       - https://github.com/floitsch/toit-chatbot/blob/main/src/chatbot.toit
>       - https://github.com/floitsch/log-uploader/blob/main/main.toit
>       - https://github.com/toitware/toit-1-wire/blob/main/examples/family.toit
>     - Sample license(s):
>       - MIT (chatbot.toit and logger.toit)
>       - BSD0 (one_wire.toit)
>   - [x] I have included a syntax highlighting grammar: https://github.com/toitware/ide-tools
>       
>   - [x] I have added a color
>     - Hex value: `#c2c9fb`
>     - Rationale: This is one of the colors that is used in the color scheme of the toit.io page
>

**Pull request merged**
