### PR TITLE
Add support for Sci-Lisp programming language.

### PR DESCRIPTION
**Pull request by chaploud**
Add [Sci-Lisp](https://github.com/chaploud/Sci-Lisp) programming language support.

## Description

- This is a new programming language.
- I have checked `CONTRIBUTING.md`

※ This programming language has just been created and is almost completely unused in GItHub, but we intend to continue to actively develop and distribute it. Is it not appropriate to add to linguist?

## Checklist:

- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.sl+(defn
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [example.sl](https://github.com/chaploud/Sci-Lisp/blob/main/examples/example.sl)
    - Sample license(s): MIT
  - [x] I have included a syntax highlighting grammar: [[URL to grammar repo]](https://github.com/chaploud/Sci-Lisp-vscode-extension)
      
  - [x] I have added a color
    - Hex value: `#413385`
    - Rationale: Language's theme color is purple, so it is chosen. 
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

### CODE REVIEW

**Comment by lildude** [comment]
> Is it not appropriate to add to linguist?

Not yet if you search results are anything to go by. They suggest you're a very very very long way from meeting our usage requirements. Your search query probably needs refining as it's definitely picking up files that don't look like your (contrived?) samples.

**Comment by chaploud** [comment]
@lildude 
Thank you for your review!
Then I would like to close this PR, and when this language becomes popular, I would like to issue another PR.

**Comment by chaploud** [comment]
I see that many PRs are marked as "pending popularity", no need to close this PR, right?

**Comment by lildude** [comment]
It's entirely up to you, but I'm leaning to closing this one for now given how low usage always to be.

**Comment by chaploud** [comment]
OK, I would close this PR.

**Pull request closed without merging**
