### PR TITLE
Change colour for OCaml

### PR DESCRIPTION
**Pull request by Teddy55Codes**
Changing the language color of OCaml.
I noticed that all Ocaml branding is orange (`#ee6a1a`) but the color shown on Github is green (`#3be133`).

## Description
I think this change is justified for the following reasons:
* The color `#3be133` was set back in 2012 in the ["Colors!" commit](https://github.com/github/linguist/commit/c3d6fc5a).
* The logo and the [official website](https://ocaml.org/) is all orange specifically `#ee6a1a`.

I picked `#ee6a1a` because it is the accent color on the [official website](https://ocaml.org/). I couldn't use to logo color due to it having a slight color gradient, but it is basically the same shade of orange. 

If you want to vote or comment on this change you can do that on this [poll](https://github.com/ocaml/ocaml/discussions/12013)

## Checklist:
- [x] **I am changing the color associated with a language**
  - [Ongoing poll] I have obtained agreement from the wider language community on this color change.
    - [official website](https://ocaml.org/) 
    - [poll](https://github.com/ocaml/ocaml/discussions/12013)
    - [poll 2 (shade)](https://github.com/ocaml/ocaml/discussions/12089)

### CODE REVIEW

**Comment by Teddy55Codes** [comment]
Ok, so recognised a potential issue with my change. OCaml is used in web development and html is also orange. Let me know if that is a problem and if a different shade with more contrast should be used or if the current green is fine.

**Comment by lildude** [comment]
> * [~] I have obtained agreement from the wider language community on this color change.

Unfortunately, this is going to be a hard requirement here. People are passionate about their colours (see https://github.com/github/linguist/pull/4319) especially when things have been in place for over 10 years as is the case here.

> Ok, so recognised a potential issue with my change. OCaml can be used in web development and html is also orange. Let me know if that is a problem and if a different shade with more contrast should be used or if the current green is fine.

Whilst similar and even identical colours are now accepted, this could be an additional cause for conflict.

**Comment by Teddy55Codes** [comment]
Thank you for your response. I will start seeking opinions from the OCaml community.

**Comment by bergerkevin** [comment]
> Thank you for your response. I will start seeking opinions from the OCaml community.



> Changing the language color of OCaml. I noticed that all Ocaml branding is orange (`#ee6a1a`) but the color shown on Github is green (`#3be133`).
> 
> ## Description
> I think this change is justified for the following reasons:
> 
> * The color `#3be133` was set back in 2012 in the ["Colors!" commit](https://github.com/github/linguist/commit/c3d6fc5a).
> * The logo and the [official website](https://ocaml.org/) is all orange specifically `#ee6a1a`.
> 
> I picked `#ee6a1a` because it is the accent color on the [official website](https://ocaml.org/). I couldn't use to logo color due to it having a slight color gradient, but it is basically the same shade of orange.
> 
> ## Checklist:
> * [x]  **I am changing the color associated with a language**
>   
>   * [~] I have obtained agreement from the wider language community on this color change.
>     
>     * [official website](https://ocaml.org/)

I don't like this color! I would prefer e. g. this color #5b4a14.

**Comment by Teddy55Codes** [comment]
> > Thank you for your response. I will start seeking opinions from the OCaml community.
> 
> > Changing the language color of OCaml. I noticed that all Ocaml branding is orange (`#ee6a1a`) but the color shown on Github is green (`#3be133`).
> > ## Description
> > I think this change is justified for the following reasons:
> > 
> > * The color `#3be133` was set back in 2012 in the ["Colors!" commit](https://github.com/github/linguist/commit/c3d6fc5a).
> > * The logo and the [official website](https://ocaml.org/) is all orange specifically `#ee6a1a`.
> > 
> > I picked `#ee6a1a` because it is the accent color on the [official website](https://ocaml.org/). I couldn't use to logo color due to it having a slight color gradient, but it is basically the same shade of orange.
> > ## Checklist:
> > 
> > * [x]   **I am changing the color associated with a language**
> >   
> >   * [~] I have obtained agreement from the wider language community on this color change.
> >     
> >     * [official website](https://ocaml.org/)
> 
> I don't like this color! I would prefer e. g. this color `#5b4a14`.

I really don't like that color. In my opinion it look very similar to [Pantone 448 C](https://en.wikipedia.org/wiki/Pantone_448_C)

**Comment by bergerkevin** [comment]
> > > Thank you for your response. I will start seeking opinions from the OCaml community.
> > 
> > 
> > > Changing the language color of OCaml. I noticed that all Ocaml branding is orange (`#ee6a1a`) but the color shown on Github is green (`#3be133`).
> > > ## Description
> > > I think this change is justified for the following reasons:
> > > 
> > > * The color `#3be133` was set back in 2012 in the ["Colors!" commit](https://github.com/github/linguist/commit/c3d6fc5a).
> > > * The logo and the [official website](https://ocaml.org/) is all orange specifically `#ee6a1a`.
> > > 
> > > I picked `#ee6a1a` because it is the accent color on the [official website](https://ocaml.org/). I couldn't use to logo color due to it having a slight color gradient, but it is basically the same shade of orange.
> > > ## Checklist:
> > > 
> > > * [x]    **I am changing the color associated with a language**
> > >   
> > >   * [~] I have obtained agreement from the wider language community on this color change.
> > >     
> > >     * [official website](https://ocaml.org/)
> > 
> > 
> > I don't like this color! I would prefer e. g. this color `#5b4a14`.
> 
> I really don't like that color. In my opinion it look very similar to [Pantone 448 C](https://en.wikipedia.org/wiki/Pantone_448_C)

Fuck you! I Love this Color!

**Comment by lildude** [comment]
Please keep the colour discussions out of this issue. Any discussion of preference should take place in the official community discussion channels (the one that needs to be referenced in the OP) for the language in question, not this issue.

**Comment by Teddy55Codes** [comment]
Hello, i don't want to seem inpatient but it has been almost 2 month since i have requested a review. I would really appreciate an answer.
@lildude

**Comment by lildude** [comment]
> Hello, i don't want to seem inpatient but it has been almost 2 month since i have requested a review. I would really appreciate an answer.

There's no rush, this change which won't take effect until the next release 😄 (I review all PRs before each release).

The number of respondents seems really low for a wider community acceptance, but I'll leave that on you to defend if someone complains 😉 (I doubt this will given the choice is closer to actual branding, but you never know.)

**Review by lildude — APPROVED** [review]
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

**Review by lildude — APPROVED** [review]

**Pull request merged**
